### ISSUE TITLE
Whats the rational of this if statement?

### ISSUE THREAD

**Issue by jsmedmar** [cancerit/vafCorrect#39]
What's the rationale of this [if statement] at `ReadVcf.pm#L909` (`if($read_counter > 1000)`)?

```perl
sub _get_read_length {
	my ($self,$sam)=@_;
	my ($mapped_length,$read_counter);
	my $iterator  = $sam->features(-iterator=>1);
		while (my $a = $iterator->next_seq) {
 			my $qseq=$a->qseq;
 			if(defined $qseq) {
				$read_counter++;
				my $len=length($qseq);
				$mapped_length->{$len}=$read_counter;
				if($read_counter > 1000){
					return $mapped_length;
				}
			}
 		}
}
```

I have tests running on very small bams that used to work. Not sure why don't return the `mapped_length` here. What are your thoughts?

[if statement]: https://github.com/cancerit/vafCorrect/blob/dev/perl/lib/Sanger/CGP/Vaf/Data/ReadVcf.pm#L909

**Comment by drjsanger** [comment]
@sb43  can confirm, but... 

Since this is calculating the read lengths in a sample bam file by iterating over all reads in the bam.  1000 reads was decided on as being enough reads to iterate through before assuming we had enough information to get an estimate of average read length, rather than iterate through every single read in a bam file.

**Comment by sb43** [comment]
@jsmedmar yes @drjsanger is right we sample through first 1000 reads to get read length estimate for library size calculation.

**Comment by jsmedmar** [comment]
That makes sense, thank you
